/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CounterServerImport } from './routes/counterServer'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CounterServerRoute = CounterServerImport.update({
  id: '/counterServer',
  path: '/counterServer',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/counterServer': {
      id: '/counterServer'
      path: '/counterServer'
      fullPath: '/counterServer'
      preLoaderRoute: typeof CounterServerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/counterServer': typeof CounterServerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/counterServer': typeof CounterServerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/counterServer': typeof CounterServerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/counterServer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/counterServer'
  id: '__root__' | '/' | '/counterServer'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CounterServerRoute: typeof CounterServerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CounterServerRoute: CounterServerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/counterServer"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/counterServer": {
      "filePath": "counterServer.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
